spring.application.name=DailyMotionMiner
server.port=8081
DailyMotionMiner.baseUri=https://api.dailymotion.com
DailyMotionMiner.videoFields=?fields=id,title,description,created_time,channel,tags,owner
VideoMiner.uri=http://localhost:8080/videominer
DailyMotionMiner.channelFields=?fields=id,name,description,created_time
DailyMotionMiner.userFields=?fields=owner.id,owner.username,owner.url,owner.avatar_720_url
DailyMotionMiner.subtitleFields=?fields=id,url,language


#Si esto lo ponemos público, habría que descomentar esto. Si no, todo el mundo vería los endpoints.
#springdoc.api-docs.enabled=false
#springdoc.swagger-ui.enabled=false