spring.application.name=PeerTubeMiner
peertube.base.url=https://peertube.tv
server.port=8082
videominer.base.url=${VIDEOMINER_URL:https://videominer-api.onrender.com/videominer}
videominer.api.key=123456789